<script setup lang="ts">
import { useCountryQuery, usePersonQuery } from '@/generated/operations' // generated by @nuxt3/graphql-codegen-module

const { result: client, loading: queryLoading } = await useCountryQuery({
  clientId: 'trevorblades',
  prefetch: false, // clientMode, need validate result in template
})

const { result: server, loading: jumpLoading, error } = await usePersonQuery({
  personInput: {
    name: 'Phil Xu',
  },
}, {
  prefetch: true, // ssrMode, default: true
})

// use clients directly $apollo.default  $apollo.trevorblades
// const { $apollo } = useNuxtApp()

</script>

<template>
  <div>
    <div>
      <h3 text-2xl font-500>
        Graphql Api
      </h3>
      <div v-if="queryLoading">
        Loading when client only
      </div>
      <div v-else-if="client && client.country">
        Client only: {{ client.country.name }}
      </div>

      <div v-if="jumpLoading">
        Loading when jump from other landing page
      </div>
      <div v-else-if="server && server.person">
        Prefetch on landing page: {{ server.person.name }}
      </div>
      <div v-else-if="error">
        {{ error }}
      </div>

      <div>
        <NuxtLink
          class="btn m-3 text-sm"
          to="/restful/page-view"
        >
          RESTful Api
        </NuxtLink>
      </div>
    </div>
  </div>
</template>
